# Generated by Django 4.1.1 on 2022-10-08 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Invoice_number', models.IntegerField(default=0)),
                ('Date', models.DateField()),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Details', models.TextField()),
                ('Image', models.ImageField(upload_to='products')),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Available_quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ordered_items',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField(default=1)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Total_price', models.IntegerField(default=0)),
                ('Order_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.order')),
                ('product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
    ]
